// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOi-9suP2Ihfg7ybuD7JsiEgm8EdOOTYs',
    appId: '1:773711962239:web:8be8aeddd3729a6ccc1f4a',
    messagingSenderId: '773711962239',
    projectId: 'voicenotes-92a03',
    authDomain: 'voicenotes-92a03.firebaseapp.com',
    storageBucket: 'voicenotes-92a03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjh1MYa2_lI3XqytmY4sE1BKNdHktQKfM',
    appId: '1:773711962239:android:9ee5780aef28d4bdcc1f4a',
    messagingSenderId: '773711962239',
    projectId: 'voicenotes-92a03',
    storageBucket: 'voicenotes-92a03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnRU7yYbxfIpLh10-XeRG092elaDfmlQ',
    appId: '1:773711962239:ios:a2fcf5ac8fd49f27cc1f4a',
    messagingSenderId: '773711962239',
    projectId: 'voicenotes-92a03',
    storageBucket: 'voicenotes-92a03.appspot.com',
    iosBundleId: 'voicenotes.yiqiu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATnRU7yYbxfIpLh10-XeRG092elaDfmlQ',
    appId: '1:773711962239:ios:009b7e9e594de8b0cc1f4a',
    messagingSenderId: '773711962239',
    projectId: 'voicenotes-92a03',
    storageBucket: 'voicenotes-92a03.appspot.com',
    iosBundleId: 'com.example.whisperGpt',
  );
}
